# Problem 67

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom in triangle.txt (right click and 'Save Link/Target As...'), a 15K text file containing a triangle with one-hundred rows.

NOTE: This is a much more difficult version of Problem 18. It is not possible to try every route to solve this problem, as there are 299 altogether! If you could check one trillion (1012) routes every second it would take over twenty billion years to check them all. There is an efficient algorithm to solve it. ;o)

In [135]:
import numpy as np

with open('p067_triangle.txt') as f:
    read_data = f.read()
    
M_strings = read_data.split('\n')
M_splited = []
for x in M_strings:
    M_splited.append(x.split(' '))
for r in range(0,99):
    for c in range(r+1,100):
        M_splited[r].append(0)
pd.DataFrame(M_splited)
M_int = np.zeros((100,100))
for r in range(0,100):
    for c in range(0,100):
        M_int[r][c] = int(M_splited[r][c])
pd.DataFrame(M_int)

for r in range(100):
    for c in range(100-1):
        #print(r, c, 15-r-1, 15-r)
        M_int[99-r-1][c] += max(M_int[99-r][c],M_int[99-r][c+1])
M_int[0][0]

7273.0

# Problem 39

If p is the perimeter of a right angle triangle with integral length sides, {a,b,c}, there are exactly three solutions for p = 120.

{20,48,52}, {24,45,51}, {30,40,50}

For which value of p ≤ 1000, is the number of solutions maximised?

In [344]:
limit_p = 118
n=1
sq_list = []
while n<limit_p:
    sq_list.append(n**2)
    n+=1
sq_list

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689]

In [330]:
import itertools

a = [1,2,3]
b = list(itertools.combinations(a, 2))
b

[(1, 2), (1, 3), (2, 3)]

# Problem 38

Take the number 192 and multiply it by each of 1, 2, and 3:

    192 × 1 = 192
    192 × 2 = 384
    192 × 3 = 576

By concatenating each product we get the 1 to 9 pandigital, 192384576. We will call 192384576 the concatenated product of 192 and (1,2,3)

The same can be achieved by starting with 9 and multiplying by 1, 2, 3, 4, and 5, giving the pandigital, 918273645, which is the concatenated product of 9 and (1,2,3,4,5).

What is the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1,2, ... , n) where n > 1?

# Problem 37

The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.

Find the sum of the only eleven primes that are both truncatable from left to right and right to left.

NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.

# Problem 36

The decimal number, 585 = 10010010012 (binary), is palindromic in both bases.

Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.

(Please note that the palindromic number, in either base, may not include leading zeros.)

In [313]:
print(sum(n for n in range(1000000) if str(n) == str(n)[::-1] and bin(n)[2:] == bin(n)[2:][::-1]))

872187

In [312]:
def is_palindromic(number):
    number_list = list(str(number))
  
    if number_list == number_list[::-1]:
        return True
    else:
        return False

def decimal_binary_palindromic(limit):
    sum_dec_bin_pal = 0
    for n in range(limit):
        if is_palindromic(n) and is_palindromic(format(n, 'b')):
            sum_dec_bin_pal += n
            #print(n, format(n, 'b'))
    print(sum_dec_bin_pal)
decimal_binary_palindromic(1000000)

872187

# Problem 35

The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.

How many circular primes are there below one million?

# Problem 34

145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: as 1! = 1 and 2! = 2 are not sums they are not included.

In [ ]:
factorials = {
				0: 1, 
				1: 1, 
				2: 2, 
				3: 6, 
				4: 24, 
				5: 120, 
				6: 720, 
				7: 5040, 
				8: 40320, 
				9: 362880
}

def returnDigits(n):
	digits = []
	while(n > 0):
		digits.append(n % 10)
		n = n // 10

	return digits

factorialSums = 0

for i in range(3, 100000):
	if i == sum(map(lambda x: factorials[x], returnDigits(i))):
		factorialSums += i

print("the sum of these factorials are", factorialSums)

In [284]:
145+40585

40730

In [292]:
for n in range(10):
    print(math.factorial(n))

1
1
2
6
24
120
720
5040
40320
362880

In [291]:
import math

def fact_digits(number):
    sum_fact = 0
    for x in str(number):
        sum_fact += math.factorial(int(x))
    return sum_fact

llimit=2
ulimit=9999999

for num in range(llimit,ulimit):
    if fact_digits(num) == num:
        print(num)

# Problem 33

The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.

We shall consider fractions like, 30/50 = 3/5, to be trivial examples.

There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

# Problem 32

We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.

The product 7254 is unusual, as the identity, 39 × 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.

Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.
HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.

# Problem 31

In England the currency is made up of pound, £, and pence, p, and there are eight coins in general circulation:

    1p, 2p, 5p, 10p, 20p, 50p, £1 (100p) and £2 (200p).

It is possible to make £2 in the following way:

    1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p

How many different ways can £2 be made using any number of coins?

In [ ]:
1p = 1p #1
2p = [2p, [1p, 1p]] #2
5p = [
    5p, 
    [2p, 2p, 1p], 
    [2p, [1p, 1p], 1p], 
    [[1p, 1p],[1p, 1p], 1p]
] #4

# Problem 30

Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:

    1634 = 14 + 64 + 34 + 44
    8208 = 84 + 24 + 04 + 84
    9474 = 94 + 44 + 74 + 44

As 1 = 14 is not a sum it is not included.

The sum of these numbers is 1634 + 8208 + 9474 = 19316.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.

# Problem 29

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    22=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

In [268]:
huge = []
limit = 101
for a in range(2,limit):
    for b in range(2,limit):
        huge.append(a**b)
huge = sorted(set(huge))
len(huge)

9183

# Problem 28

Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:

21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13

It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?

In [258]:
sum_diag = 1
addition1 = 1
addition2 = 3

rozmiar = 1001
for i in range(1,rozmiar//2+1):
    
    addition1 += 4*i
    sum_diag += addition1 # 5
    
    addition1 += 4*i
    sum_diag += addition1 # 9

for n in range(1,rozmiar): # wykonane 4x
    
    sum_diag += addition2 
    addition2 += 2*(n+1)
          
sum_diag

669171001

# Problem 27

Euler discovered the remarkable quadratic formula:

n2+n+41

It turns out that the formula will produce 40 primes for the consecutive integer values 0≤n≤39
. However, when n=40,402+40+41=40(40+1)+41 is divisible by 41, and certainly when n=41,412+41+41

is clearly divisible by 41.

The incredible formula n2−79n+1601
was discovered, which produces 80 primes for the consecutive values 0≤n≤79

. The product of the coefficients, −79 and 1601, is −126479.

Considering quadratics of the form:

    n2+an+b

, where |a|<1000 and |b|≤1000

where |n|
is the modulus/absolute value of n
e.g. |11|=11 and |−4|=4

Find the product of the coefficients, a
and b, for the quadratic expression that produces the maximum number of primes for consecutive values of n, starting with n=0.

# Problem 26

A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

    1/2	= 	0.5
    1/3	= 	0.(3)
    1/4	= 	0.25
    1/5	= 	0.2
    1/6	= 	0.1(6)
    1/7	= 	0.(142857)
    1/8	= 	0.125
    1/9	= 	0.(1)
    1/10	= 	0.1 

Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.

In [236]:
import re
p = re.compile('(.+?)\1+$')
test_str = "1234123412341234"

re.findall(p, test_str)

[]

In [213]:
for d in range(1,11):
    print(1/d)

1.0
0.5
0.3333333333333333
0.25
0.2
0.16666666666666666
0.14285714285714285
0.125
0.1111111111111111
0.1

# Problem 25

The Fibonacci sequence is defined by the recurrence relation:

    Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.

Hence the first 12 terms will be:

    F1 = 1
    F2 = 1
    F3 = 2
    F4 = 3
    F5 = 5
    F6 = 8
    F7 = 13
    F8 = 21
    F9 = 34
    F10 = 55
    F11 = 89
    F12 = 144

The 12th term, F12, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [232]:
def fib(n):
    a = 1
    b = 0
    while n > 1:
        a, b = a+b, a
        n = n - 1
    return a
    
def digits(n):
    return len(str(n))

def main(limit):
    n = 1
    while digits(fib(n))<limit:
        n += 1
    return n

main(1000)

4782

In [216]:
a = [1,
7,
12,
17,
21,
26,
31,
36,
40]
for n in range(len(a)-1):
    print(a[n+1]-a[n])

6
5
5
4
5
5
5
4

In [222]:
count = 1
k = 40
index = 9
while index<=1000:
    if count % 4 != 0:
        k += 5
        count+=1
    else:
        k += 4
        count=1
    index +=1
    print(index, k)

10 45
11 50
12 55
13 59
14 64
15 69
16 74
17 78
18 83
19 88
20 93
21 97
22 102
23 107
24 112
25 116
26 121
27 126
28 131
29 135
30 140
31 145
32 150
33 154
34 159
35 164
36 169
37 173
38 178
39 183
40 188
41 192
42 197
43 202
44 207
45 211
46 216
47 221
48 226
49 230
50 235
51 240
52 245
53 249
54 254
55 259
56 264
57 268
58 273
59 278
60 283
61 287
62 292
63 297
64 302
65 306
66 311
67 316
68 321
69 325
70 330
71 335
72 340
73 344
74 349
75 354
76 359
77 363
78 368
79 373
80 378
81 382
82 387
83 392
84 397
85 401
86 406
87 411
88 416
89 420
90 425
91 430
92 435
93 439
94 444
95 449
96 454
97 458
98 463
99 468
100 473
101 477
102 482
103 487
104 492
105 496
106 501
107 506
108 511
109 515
110 520
111 525
112 530
113 534
114 539
115 544
116 549
117 553
118 558
119 563
120 568
121 572
122 577
123 582
124 587
125 591
126 596
127 601
128 606
129 610
130 615
131 620
132 625
133 629
134 634
135 639
136 644
137 648
138 653
139 658
140 663
141 667
142 672
143 677
144 682
145 686
146 691
147 696
148 701
149 705
150 710
151 715
152 720
153 724
154 729
155 734
156 739
157 743
158 748
159 753
160 758
161 762
162 767
163 772
164 777
165 781
166 786
167 791
168 796
169 800
170 805
171 810
172 815
173 819
174 824
175 829
176 834
177 838
178 843
179 848
180 853
181 857
182 862
183 867
184 872
185 876
186 881
187 886
188 891
189 895
190 900
191 905
192 910
193 914
194 919
195 924
196 929
197 933
198 938
199 943
200 948
201 952
202 957
203 962
204 967
205 971
206 976
207 981
208 986
209 990
210 995
211 1000
212 1005
213 1009
214 1014
215 1019
216 1024
217 1028
218 1033
219 1038
220 1043
221 1047
222 1052
223 1057
224 1062
225 1066
226 1071
227 1076
228 1081
229 1085
230 1090
231 1095
232 1100
233 1104
234 1109
235 1114
236 1119
237 1123
238 1128
239 1133
240 1138
241 1142
242 1147
243 1152
244 1157
245 1161
246 1166
247 1171
248 1176
249 1180
250 1185
251 1190
252 1195
253 1199
254 1204
255 1209
256 1214
257 1218
258 1223
259 1228
260 1233
261 1237
262 1242
263 1247
264 1252
265 1256
266 1261
267 1266
268 1271
269 1275
270 1280
271 1285
272 1290
273 1294
274 1299
275 1304
276 1309
277 1313
278 1318
279 1323
280 1328
281 1332
282 1337
283 1342
284 1347
285 1351
286 1356
287 1361
288 1366
289 1370
290 1375
291 1380
292 1385
293 1389
294 1394
295 1399
296 1404
297 1408
298 1413
299 1418
300 1423
301 1427
302 1432
303 1437
304 1442
305 1446
306 1451
307 1456
308 1461
309 1465
310 1470
311 1475
312 1480
313 1484
314 1489
315 1494
316 1499
317 1503
318 1508
319 1513
320 1518
321 1522
322 1527
323 1532
324 1537
325 1541
326 1546
327 1551
328 1556
329 1560
330 1565
331 1570
332 1575
333 1579
334 1584
335 1589
336 1594
337 1598
338 1603
339 1608
340 1613
341 1617
342 1622
343 1627
344 1632
345 1636
346 1641
347 1646
348 1651
349 1655
350 1660
351 1665
352 1670
353 1674
354 1679
355 1684
356 1689
357 1693
358 1698
359 1703
360 1708
361 1712
362 1717
363 1722
364 1727
365 1731
366 1736
367 1741
368 1746
369 1750
370 1755
371 1760
372 1765
373 1769
374 1774
375 1779
376 1784
377 1788
378 1793
379 1798
380 1803
381 1807
382 1812
383 1817
384 1822
385 1826
386 1831
387 1836
388 1841
389 1845
390 1850
391 1855
392 1860
393 1864
394 1869
395 1874
396 1879
397 1883
398 1888
399 1893
400 1898
401 1902
402 1907
403 1912
404 1917
405 1921
406 1926
407 1931
408 1936
409 1940
410 1945
411 1950
412 1955
413 1959
414 1964
415 1969
416 1974
417 1978
418 1983
419 1988
420 1993
421 1997
422 2002
423 2007
424 2012
425 2016
426 2021
427 2026
428 2031
429 2035
430 2040
431 2045
432 2050
433 2054
434 2059
435 2064
436 2069
437 2073
438 2078
439 2083
440 2088
441 2092
442 2097
443 2102
444 2107
445 2111
446 2116
447 2121
448 2126
449 2130
450 2135
451 2140
452 2145
453 2149
454 2154
455 2159
456 2164
457 2168
458 2173
459 2178
460 2183
461 2187
462 2192
463 2197
464 2202
465 2206
466 2211
467 2216
468 2221
469 2225
470 2230
471 2235
472 2240
473 2244
474 2249
475 2254
476 2259
477 2263
478 2268
479 2273
480 2278
481 2282
482 2287
483 2292
484 2297
485 2301
486 2306
487 2311
488 2316
489 2320
490 2325
491 2330
492 2335
493 2339
494 2344
495 2349
496 2354
497 2358
498 2363
499 2368
500 2373
501 2377
502 2382
503 2387
504 2392
505 2396
506 2401
507 2406
508 2411
509 2415
510 2420
511 2425
512 2430
513 2434
514 2439
515 2444
516 2449
517 2453
518 2458
519 2463
520 2468
521 2472
522 2477
523 2482
524 2487
525 2491
526 2496
527 2501
528 2506
529 2510
530 2515
531 2520
532 2525
533 2529
534 2534
535 2539
536 2544
537 2548
538 2553
539 2558
540 2563
541 2567
542 2572
543 2577
544 2582
545 2586
546 2591
547 2596
548 2601
549 2605
550 2610
551 2615
552 2620
553 2624
554 2629
555 2634
556 2639
557 2643
558 2648
559 2653
560 2658
561 2662
562 2667
563 2672
564 2677
565 2681
566 2686
567 2691
568 2696
569 2700
570 2705
571 2710
572 2715
573 2719
574 2724
575 2729
576 2734
577 2738
578 2743
579 2748
580 2753
581 2757
582 2762
583 2767
584 2772
585 2776
586 2781
587 2786
588 2791
589 2795
590 2800
591 2805
592 2810
593 2814
594 2819
595 2824
596 2829
597 2833
598 2838
599 2843
600 2848
601 2852
602 2857
603 2862
604 2867
605 2871
606 2876
607 2881
608 2886
609 2890
610 2895
611 2900
612 2905
613 2909
614 2914
615 2919
616 2924
617 2928
618 2933
619 2938
620 2943
621 2947
622 2952
623 2957
624 2962
625 2966
626 2971
627 2976
628 2981
629 2985
630 2990
631 2995
632 3000
633 3004
634 3009
635 3014
636 3019
637 3023
638 3028
639 3033
640 3038
641 3042
642 3047
643 3052
644 3057
645 3061
646 3066
647 3071
648 3076
649 3080
650 3085
651 3090
652 3095
653 3099
654 3104
655 3109
656 3114
657 3118
658 3123
659 3128
660 3133
661 3137
662 3142
663 3147
664 3152
665 3156
666 3161
667 3166
668 3171
669 3175
670 3180
671 3185
672 3190
673 3194
674 3199
675 3204
676 3209
677 3213
678 3218
679 3223
680 3228
681 3232
682 3237
683 3242
684 3247
685 3251
686 3256
687 3261
688 3266
689 3270
690 3275
691 3280
692 3285
693 3289
694 3294
695 3299
696 3304
697 3308
698 3313
699 3318
700 3323
701 3327
702 3332
703 3337
704 3342
705 3346
706 3351
707 3356
708 3361
709 3365
710 3370
711 3375
712 3380
713 3384
714 3389
715 3394
716 3399
717 3403
718 3408
719 3413
720 3418
721 3422
722 3427
723 3432
724 3437
725 3441
726 3446
727 3451
728 3456
729 3460
730 3465
731 3470
732 3475
733 3479
734 3484
735 3489
736 3494
737 3498
738 3503
739 3508
740 3513
741 3517
742 3522
743 3527
744 3532
745 3536
746 3541
747 3546
748 3551
749 3555
750 3560
751 3565
752 3570
753 3574
754 3579
755 3584
756 3589
757 3593
758 3598
759 3603
760 3608
761 3612
762 3617
763 3622
764 3627
765 3631
766 3636
767 3641
768 3646
769 3650
770 3655
771 3660
772 3665
773 3669
774 3674
775 3679
776 3684
777 3688
778 3693
779 3698
780 3703
781 3707
782 3712
783 3717
784 3722
785 3726
786 3731
787 3736
788 3741
789 3745
790 3750
791 3755
792 3760
793 3764
794 3769
795 3774
796 3779
797 3783
798 3788
799 3793
800 3798
801 3802
802 3807
803 3812
804 3817
805 3821
806 3826
807 3831
808 3836
809 3840
810 3845
811 3850
812 3855
813 3859
814 3864
815 3869
816 3874
817 3878
818 3883
819 3888
820 3893
821 3897
822 3902
823 3907
824 3912
825 3916
826 3921
827 3926
828 3931
829 3935
830 3940
831 3945
832 3950
833 3954
834 3959
835 3964
836 3969
837 3973
838 3978
839 3983
840 3988
841 3992
842 3997
843 4002
844 4007
845 4011
846 4016
847 4021
848 4026
849 4030
850 4035
851 4040
852 4045
853 4049
854 4054
855 4059
856 4064
857 4068
858 4073
859 4078
860 4083
861 4087
862 4092
863 4097
864 4102
865 4106
866 4111
867 4116
868 4121
869 4125
870 4130
871 4135
872 4140
873 4144
874 4149
875 4154
876 4159
877 4163
878 4168
879 4173
880 4178
881 4182
882 4187
883 4192
884 4197
885 4201
886 4206
887 4211
888 4216
889 4220
890 4225
891 4230
892 4235
893 4239
894 4244
895 4249
896 4254
897 4258
898 4263
899 4268
900 4273
901 4277
902 4282
903 4287
904 4292
905 4296
906 4301
907 4306
908 4311
909 4315
910 4320
911 4325
912 4330
913 4334
914 4339
915 4344
916 4349
917 4353
918 4358
919 4363
920 4368
921 4372
922 4377
923 4382
924 4387
925 4391
926 4396
927 4401
928 4406
929 4410
930 4415
931 4420
932 4425
933 4429
934 4434
935 4439
936 4444
937 4448
938 4453
939 4458
940 4463
941 4467
942 4472
943 4477
944 4482
945 4486
946 4491
947 4496
948 4501
949 4505
950 4510
951 4515
952 4520
953 4524
954 4529
955 4534
956 4539
957 4543
958 4548
959 4553
960 4558
961 4562
962 4567
963 4572
964 4577
965 4581
966 4586
967 4591
968 4596
969 4600
970 4605
971 4610
972 4615
973 4619
974 4624
975 4629
976 4634
977 4638
978 4643
979 4648
980 4653
981 4657
982 4662
983 4667
984 4672
985 4676
986 4681
987 4686
988 4691
989 4695
990 4700
991 4705
992 4710
993 4714
994 4719
995 4724
996 4729
997 4733
998 4738
999 4743
1000 4748
1001 4752

# Problem 24

A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

012   021   102   120   201   210

What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

# Problem 23

A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

# Problem 22

Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.

What is the total of all the name scores in the file?

In [190]:
with open('p022_names.txt') as file:
    text = file.read()

names = sorted( name.replace('"','') for name in text.split(',') )

def value(name):
    return sum(  ord(c) for c in name ) - (ord('A') - 1) * len(name)

total = sum( (position + 1) * value(name) for position, name in enumerate(names) )

print( total )

871198282

In [184]:
with open('p022_names.txt', 'r') as f:
    data_names = f.read()
    data_names = data_names.replace('"','')
    data_names = data_names.split(',')
    data_names.sort()
#data_names

from string import ascii_uppercase as al
alphabet_dic = {x:i for i, x in enumerate(al, 1)}
#alphabet_dic

count = 0
all_scores = 0
for n in data_names:
    sum_of_letters = 0
    for l in n:
        sum_of_letters += alphabet_dic[l]
        #print(alphabet_dic[l])
    count += 1
    all_scores += count*sum_of_letters
    #print(count, n, sum_of_letters, count*sum_of_letters)
print(all_scores)

871198282

# Problem 21

Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.

For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

Evaluate the sum of all the amicable numbers under 10000.

# Problem 20

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [151]:
import math
digit_sum = 0
num = math.factorial(100)
for i in str(num):
    digit_sum += int(i)
print(digit_sum)

648

In [150]:
def sil(n):
    f = lambda x: x * f(x-1) if x != 0 else 1
    return f(n)

def sum_dig(n):
    sum_d = 0
    for d in str(n):
        sum_d += int(d)
    return sum_d

num = 100
print(sil(num), sum_dig(sil(num)))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000 648

# Problem 19

You are given the following information, but you may prefer to do some research for yourself.

    1 Jan 1900 was a Monday.
    Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
    And on leap years, twenty-nine.
    A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

# Problem 18

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [89]:
triangle_matrix = [
[75, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
[95, 64, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
[17, 47, 82, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
[18, 35, 87, 10, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
[20, 4, 82, 47, 65, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
[19, 1, 23, 75, 3, 34, 0,  0,  0,  0,  0,  0,  0,  0,  0],
[88, 2, 77, 73, 7, 63, 67, 0,  0,  0,  0,  0,  0,  0,  0],
[99, 65, 4, 28, 6, 16, 70, 92, 0,  0,  0,  0,  0,  0,  0],
[41, 41, 26, 56, 83, 40, 80, 70, 33, 0,  0,  0,  0,  0,  0],
[41, 48, 72, 33, 47, 32, 37, 16, 94, 29, 0,  0,  0,  0,  0],
[53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14, 0,  0,  0,  0],
[70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57, 0,  0,  0],
[91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48, 0,  0],
[63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31, 0],
[4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]
]

In [90]:
import pandas as pd
M = []
M = triangle_matrix.copy()
for r in range(15):
    for c in range(15-1):
        #print(r, c, 15-r-1, 15-r)
        M[14-r-1][c] += max(M[14-r][c],M[14-r][c+1])
pd.DataFrame(M)

      0     1     2    3    4    5    6    7    8    9    10   11   12  13  14
0   1074   999   935  792  782  717  683  616  487  322  247  233  148  54   0
1    995   999   935  792  782  717  683  616  487  322  247  233  148  54   0
2    818   900   935  792  782  717  683  616  487  322  247  233  148  54   0
3    704   801   853  792  782  717  683  616  487  322  247  233  148  54   0
4    686   640   766  731  782  717  683  616  487  322  247  233  148  54   0
5    666   614   636  684  660  717  683  616  487  322  247  233  148  54   0
6    647   501   613  609  533  657  683  616  487  322  247  233  148  54   0
7    559   499   479  536  514  526  594  616  487  322  247  233  148  54   0
8    460   434   419  475  508  470  510  524  487  322  247  233  148  54   0
9    419   365   393  387  419  425  430  376  454  322  247  233  148  54   0
10   378   317   231  321  354  372  393  354  360  293  247  233  148  54   0
11   325   246   187  178  256  329  273  302  263  242  193  233  148  54   0
12   255   235   154  150  140  179  256  209  224  172  174  176  148  54   0
13   125   164   102   95  112  123  165  128  166  109  122  147  100  54   0
14  1078  1061  1033  819  805  726  753  714  560  415  285  286  208  58  23

# Problem 17

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [41]:
ones = ["", "one ","two ","three ","four ", "five ", "six ","seven ","eight ","nine ","ten ","eleven ","twelve ", "thirteen ", "fourteen ", "fifteen ","sixteen ","seventeen ", "eighteen ","nineteen "]
     
twenties = ["","","twenty ","thirty ","forty ", "fifty ","sixty ","seventy ","eighty ","ninety "]
     
thousands = ["","thousand ","million ", "billion ", "trillion ", "quadrillion ", "quintillion ", "sextillion ", "septillion ","octillion ", "nonillion ", "decillion ", "undecillion ", "duodecillion ", "tredecillion ", "quattuordecillion ", "quindecillion", "sexdecillion ", "septendecillion ", "octodecillion ", "novemdecillion ", "vigintillion "]
     
     
def num999(n):
    c = int(n % 10) # singles digit
    b = int(((n % 100) - c) / 10) # tens digit
    a = int(((n % 1000) - (b * 10) - c) / 100) # hundreds digit
    #print(a,b,c)
    t = ""
    h = ""
    if a != 0 and b == 0 and c == 0:
        t = ones[a] + "hundred "
    elif a != 0:
        t = ones[a] + "hundred and "
    if b <= 1:
        h = ones[n%100]
    elif b > 1:
        h = twenties[b] + ones[c]
    st = t + h
    return st
     
def num2word(num):
    if num == 0: return 'zero'
    i = 3
    n = str(num)
    word = ""
    k = 0
    while(i == 3):
        nw = n[-i:]
        n = n[:-i]
        if int(nw) == 0:
            word = num999(int(nw)) + thousands[int(nw)] + word
        else:
            word = num999(int(nw)) + thousands[k] + word
        if n == '':
            i = i+1
        k += 1
    return word[:-1]

In [52]:
sum_of_letters = 0
for n in range(1,1001):
    sum_of_letters += len(num2word(n).replace(' ',''))
sum_of_letters

21124

In [53]:
import inflect

def lettersgenerator():
    letter_counter = 0
    p = inflect.engine()
    for i in range(1,1001):
        letters = p.number_to_words(i)
        letters = letters.replace('-', '')
        letters = letters.replace(',', '')
        letters = letters.replace(' ', '')
        letter_counter = letter_counter + len(letters)

    return letter_counter

lettersgenerator()

ImportError: No module named 'inflect'

In [23]:
import PyNum2Word
num2words.to_card(1555)

ImportError: No module named 'PyNum2Word'

In [54]:
digits = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
teens = ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
tens = ["twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]

letters = 190 * sum(map(len, digits))
letters += 10 * sum(map(len, teens))
letters += 100 * sum(map(len, tens))
letters += 900 * len("hundred")
letters += 9 * 99 * len("and")
letters += len("onethousand")

print(letters)

21124

In [ ]:
def read_number(number):
    units = {0: '', 1:'one', 2:'two', 3:'three', 4:'four', 5:'five', 6:'six', 7:'seven', 8:'eight', 9:'nine'}
    teens = {10:'ten', 11:'eleven', 12:'twelve', 13:'thirteen', 14:'fourteen', 15:'fifteen', 16:'sixteen', 17:'seventeen', 18:'eighteen', 19:'nineteen'}

# Problem 16

2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

In [20]:
potega = 2**1000
digits = str(potega)
sum_of_dig = 0
for dig in digits:
    sum_of_dig += int(dig)
print(potega, sum_of_dig)

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376 1366

In [17]:
for n in range(16):
    potega = 2**n
    digits = list(str(potega))
    sum_of_dig = 0
    for dig in digits:
        sum_of_dig += int(dig)
    print(potega, sum_of_dig)

1 1
2 2
4 4
8 8
16 7
32 5
64 10
128 11
256 13
512 8
1024 7
2048 14
4096 19
8192 20
16384 22
32768 26

# Problem 15

Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

# Problem 14

The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:
13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

# Problem 13

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.
37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690

In [7]:
one_hundret_numbers = [
37107287533902102798797998220837590246510135740250,
46376937677490009712648124896970078050417018260538,
74324986199524741059474233309513058123726617309629,
91942213363574161572522430563301811072406154908250,
23067588207539346171171980310421047513778063246676,
89261670696623633820136378418383684178734361726757,
28112879812849979408065481931592621691275889832738,
44274228917432520321923589422876796487670272189318,
47451445736001306439091167216856844588711603153276,
70386486105843025439939619828917593665686757934951,
62176457141856560629502157223196586755079324193331,
64906352462741904929101432445813822663347944758178,
92575867718337217661963751590579239728245598838407,
58203565325359399008402633568948830189458628227828,
80181199384826282014278194139940567587151170094390,
35398664372827112653829987240784473053190104293586,
86515506006295864861532075273371959191420517255829,
71693888707715466499115593487603532921714970056938,
54370070576826684624621495650076471787294438377604,
53282654108756828443191190634694037855217779295145,
36123272525000296071075082563815656710885258350721,
45876576172410976447339110607218265236877223636045,
17423706905851860660448207621209813287860733969412,
81142660418086830619328460811191061556940512689692,
51934325451728388641918047049293215058642563049483,
62467221648435076201727918039944693004732956340691,
15732444386908125794514089057706229429197107928209,
55037687525678773091862540744969844508330393682126,
18336384825330154686196124348767681297534375946515,
80386287592878490201521685554828717201219257766954,
78182833757993103614740356856449095527097864797581,
16726320100436897842553539920931837441497806860984,
48403098129077791799088218795327364475675590848030,
87086987551392711854517078544161852424320693150332,
59959406895756536782107074926966537676326235447210,
69793950679652694742597709739166693763042633987085,
41052684708299085211399427365734116182760315001271,
65378607361501080857009149939512557028198746004375,
35829035317434717326932123578154982629742552737307,
94953759765105305946966067683156574377167401875275,
88902802571733229619176668713819931811048770190271,
25267680276078003013678680992525463401061632866526,
36270218540497705585629946580636237993140746255962,
24074486908231174977792365466257246923322810917141,
91430288197103288597806669760892938638285025333403,
34413065578016127815921815005561868836468420090470,
23053081172816430487623791969842487255036638784583,
11487696932154902810424020138335124462181441773470,
63783299490636259666498587618221225225512486764533,
67720186971698544312419572409913959008952310058822,
95548255300263520781532296796249481641953868218774,
76085327132285723110424803456124867697064507995236,
37774242535411291684276865538926205024910326572967,
23701913275725675285653248258265463092207058596522,
29798860272258331913126375147341994889534765745501,
18495701454879288984856827726077713721403798879715,
38298203783031473527721580348144513491373226651381,
34829543829199918180278916522431027392251122869539,
40957953066405232632538044100059654939159879593635,
29746152185502371307642255121183693803580388584903,
41698116222072977186158236678424689157993532961922,
62467957194401269043877107275048102390895523597457,
23189706772547915061505504953922979530901129967519,
86188088225875314529584099251203829009407770775672,
11306739708304724483816533873502340845647058077308,
82959174767140363198008187129011875491310547126581,
97623331044818386269515456334926366572897563400500,
42846280183517070527831839425882145521227251250327,
55121603546981200581762165212827652751691296897789,
32238195734329339946437501907836945765883352399886,
75506164965184775180738168837861091527357929701337,
62177842752192623401942399639168044983993173312731,
32924185707147349566916674687634660915035914677504,
99518671430235219628894890102423325116913619626622,
73267460800591547471830798392868535206946944540724,
76841822524674417161514036427982273348055556214818,
97142617910342598647204516893989422179826088076852,
87783646182799346313767754307809363333018982642090,
10848802521674670883215120185883543223812876952786,
71329612474782464538636993009049310363619763878039,
62184073572399794223406235393808339651327408011116,
66627891981488087797941876876144230030984490851411,
60661826293682836764744779239180335110989069790714,
85786944089552990653640447425576083659976645795096,
66024396409905389607120198219976047599490197230297,
64913982680032973156037120041377903785566085089252,
16730939319872750275468906903707539413042652315011,
94809377245048795150954100921645863754710598436791,
78639167021187492431995700641917969777599028300699,
15368713711936614952811305876380278410754449733078,
40789923115535562561142322423255033685442488917353,
44889911501440648020369068063960672322193204149535,
41503128880339536053299340368006977710650566631954,
81234880673210146739058568557934581403627822703280,
82616570773948327592232845941706525094512325230608,
22918802058777319719839450180888072429661980811197,
77158542502016545090413245809786882778948721859617,
72107838435069186155435662884062257473692284509516,
20849603980134001723930671666823555245252804609722,
53503534226472524250874054075591789781264330331690,
]

In [15]:
''.join(list(str(sum(one_hundret_numbers)))[0:10])

'5537376230'

# Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

# Problem 11

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08

49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00

81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65

52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91

22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80

24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50

32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70

67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21

24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72

21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95

78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92

16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57

86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58

19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40

04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66

88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69

04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36

20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16

20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54

01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [282]:
grid = [[8, 2, 22, 97, 38, 15, 0, 40, 0, 75, 4, 5, 7, 78, 52, 12, 50, 77, 91, 8],
[49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48, 4, 56, 62, 0],
[81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30, 3, 49, 13, 36, 65],
[52, 70, 95, 23, 4, 60, 11, 42, 69, 24, 68, 56, 1, 32, 56, 71, 37, 2, 36, 91],
[22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28, 66, 33, 13, 80],
[24, 47, 32, 60, 99, 3, 45, 2, 44, 75, 33, 53, 78, 36, 84, 20, 35, 17, 12, 50],
[32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66, 18, 38, 64, 70],
[67, 26, 20, 68, 2, 62, 12, 20, 95, 63, 94, 39, 63, 8, 40, 91, 66, 49, 94, 21],
[24, 55, 58, 5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88, 34, 89, 63, 72],
[21, 36, 23, 9, 75, 0, 76, 44, 20, 45, 35, 14, 0, 61, 33, 97, 34, 31, 33, 95],
[78, 17, 53, 28, 22, 75, 31, 67, 15, 94, 3, 80, 4, 62, 16, 14, 9, 53, 56, 92],
[16, 39, 5, 42, 96, 35, 31, 47, 55, 58, 88, 24, 0, 17, 54, 24, 36, 29, 85, 57],
[86, 56, 0, 48, 35, 71, 89, 7, 5, 44, 44, 37, 44, 60, 21, 58, 51, 54, 17, 58],
[19, 80, 81, 68, 5, 94, 47, 69, 28, 73, 92, 13, 86, 52, 17, 77, 4, 89, 55, 40],
[4, 52, 8, 83, 97, 35, 99, 16, 7, 97, 57, 32, 16, 26, 26, 79, 33, 27, 98, 66],
[88, 36, 68, 87, 57, 62, 20, 72, 3, 46, 33, 67, 46, 55, 12, 32, 63, 93, 53, 69],
[4, 42, 16, 73, 38, 25, 39, 11, 24, 94, 72, 18, 8, 46, 29, 32, 40, 62, 76, 36],
[20, 69, 36, 41, 72, 30, 23, 88, 34, 62, 99, 69, 82, 67, 59, 85, 74, 4, 36, 16],
[20, 73, 35, 29, 78, 31, 90, 1, 74, 31, 49, 71, 48, 86, 81, 16, 23, 57, 5, 54],
[1, 70, 54, 71, 83, 51, 54, 69, 16, 92, 33, 48, 61, 43, 52, 1, 89, 19, 67, 48]]

In [314]:
import numpy as np
np_grid = np.array(grid)

width = 20
height = 20
temp = []
mult_len = 4

# left - right
mult_max = 1
wiersz_max = 1
kolumna_max = 1
temp_max = []
for h in range(height):
    for w in range(width-mult_len+1):
        temp = grid[h][w:w+mult_len]
        mult = 1
        for x in temp:
            mult *= x
        if mult > mult_max:
            mult_max = mult
            wiersz_max = h+1
            kolumna_max = w+1
            temp_max = temp
print('znaleziony max poziomo: ', temp_max, mult_max, 'wiersz: ', wiersz_max, 'kolumna: ', kolumna_max)
        
# up - down
mult_max = 1
wiersz_max = 1
kolumna_max = 1
temp_max = []
for w in range(width):
    for h in range(height-mult_len+1):
        temp = np_grid[h:h+mult_len,w:w+1]
        mult = 1
        for x in temp:
            mult *= x
        if mult > mult_max:
            mult_max = mult
            wiersz_max = h+1
            kolumna_max = w+1
            temp_max = temp
print('znaleziony max pionowo: ',temp_max.T, mult_max, 'wiersz: ', wiersz_max, 'kolumna: ', kolumna_max)
# diagonaly backslash
mult_max = 1
wiersz_max = 1
kolumna_max = 1
temp_max = []
for h in range(height-mult_len+1):
    for w in range(width-mult_len+1):
        m1 = grid[h][w]
        m2 = grid[h+1][w+1]
        m3 = grid[h+2][w+2]
        m4 = grid[h+3][w+3]
        mult = m1*m2*m3*m4
        if mult > mult_max:
            mult_max = mult
            wiersz_max = h+1
            kolumna_max = w+1
            temp_max = [m1,m2,m3,m4]
print('znaleziony max diagonaly backslash: ',temp_max, mult_max, 'wiersz: ', wiersz_max, 'kolumna: ', kolumna_max)

# diagonaly slash
mult_max = 1
wiersz_max = 1
kolumna_max = 1
temp_max = []
for h in range(height-mult_len+1):
    for w in range(width-mult_len+1):
        m1 = grid[h][w+3]
        m2 = grid[h+1][w+2]
        m3 = grid[h+2][w+1]
        m4 = grid[h+3][w]
        mult = m1*m2*m3*m4
        if mult > mult_max:
            mult_max = mult
            wiersz_max = h+1
            kolumna_max = w+3+1
            temp_max = [m1,m2,m3,m4]
print('znaleziony max diagonaly slash: ',temp_max, mult_max, 'wiersz: ', wiersz_max, 'kolumna: ', kolumna_max)

znaleziony max poziomo:  [78, 78, 96, 83] 48477312 wiersz:  9 kolumna:  11
znaleziony max pionowo:  [[66 91 88 97]] [51267216] wiersz:  7 kolumna:  16
znaleziony max diagonaly backslash:  [94, 99, 71, 61] 40304286 wiersz:  17 kolumna:  10
znaleziony max diagonaly slash:  [89, 94, 97, 87] 70600674 wiersz:  13 kolumna:  7

# Problem 10

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

# Problem 9

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a2 + b2 = c2

For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

# Problem 8


The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

brute force:

In [276]:
big_number = list(str(7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450))
#big_number = list(str(7666717653133062491922511))
len_big_number = len(big_number)
how_long = 13
list_all = []
max_mult = 1
for i in range(len_big_number - how_long+1):
    temp = big_number[i:i+how_long]
    mult = 1
    for el in temp:
        mult *= int(el)
    #list_all.append([temp[:], mult])
    if mult > max_mult:
        list_all.append([temp[:], mult])
        max_mult = mult
    #list_all.append(mult)
    #print(temp, adjacent)
list_all
#list_all[::1]

[[['7', '3', '1', '6', '7', '1', '7', '6', '5', '3', '1', '3', '3'], 5000940],
 [['4', '9', '1', '9', '2', '2', '5', '1', '1', '9', '6', '7', '4'], 9797760],
 [['9', '2', '2', '5', '1', '1', '9', '6', '7', '4', '4', '2', '6'], 13063680],
 [['2', '5', '1', '1', '9', '6', '7', '4', '4', '2', '6', '5', '7'], 25401600],
 [['5', '1', '1', '9', '6', '7', '4', '4', '2', '6', '5', '7', '4'], 50803200],
 [['1', '1', '9', '6', '7', '4', '4', '2', '6', '5', '7', '4', '7'], 71124480],
 [['1', '9', '6', '7', '4', '4', '2', '6', '5', '7', '4', '7', '4'],
  284497920],
 [['9', '6', '7', '4', '4', '2', '6', '5', '7', '4', '7', '4', '2'],
  568995840],
 [['5', '3', '4', '9', '1', '9', '4', '9', '3', '4', '9', '6', '9'],
  1020366720],
 [['3', '4', '9', '1', '9', '4', '9', '3', '4', '9', '6', '9', '8'],
  1632586752],
 [['9', '1', '9', '4', '9', '3', '4', '9', '6', '9', '8', '3', '5'],
  2040733440],
 [['8', '6', '9', '4', '7', '8', '8', '5', '1', '8', '4', '3', '8'],
  2972712960],
 [['4', '3', '5', '5', '7', '6', '6', '8', '9', '6', '6', '4', '8'],
  6270566400],
 [['3', '5', '5', '7', '6', '6', '8', '9', '6', '6', '4', '8', '9'],
  14108774400],
 [['5', '5', '7', '6', '6', '8', '9', '6', '6', '4', '8', '9', '5'],
  23514624000]]

myslalem, ze adjacent digits to liczby o +1, 0, -1 od siebie rozne

In [257]:
big_number = list(str(7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450))
#big_number = list(str(7666717653133062491922511))
len_big_number = len(big_number)
how_long = 4
list_adjacent = []

for i in range(len_big_number - how_long+1):
    temp = big_number[i:i+how_long]
    adjacent = False
    for n in range(1,how_long):
        diff = int(temp[n])-int(temp[n-1])
        if diff == 1 or diff == 0 or diff == -1:
            adjacent = True
        else:
            adjacent = False
            break
    if adjacent == True:
        mult = 1
        for el in temp:
            mult *= int(el)
        list_adjacent.append([temp[:], mult])
        #list_adjacent.append(mult)
    else:
        pass
    #print(temp, adjacent)
#max(list_adjacent)
list_adjacent

[[['1', '1', '1', '2'], 2],
 [['1', '1', '1', '2'], 2],
 [['1', '1', '2', '1'], 2],
 [['4', '4', '4', '4'], 256],
 [['9', '9', '8', '7'], 4536],
 [['7', '7', '6', '6'], 1764],
 [['7', '6', '6', '5'], 1260],
 [['0', '0', '1', '0'], 0],
 [['6', '7', '8', '8'], 2688],
 [['5', '4', '5', '4'], 400],
 [['9', '9', '8', '9'], 5832],
 [['4', '3', '4', '5'], 240],
 [['6', '5', '6', '7'], 1260],
 [['4', '5', '6', '6'], 720],
 [['5', '6', '6', '5'], 900],
 [['7', '6', '5', '4'], 840],
 [['6', '5', '4', '5'], 600],
 [['5', '4', '5', '6'], 600],
 [['3', '2', '1', '1'], 6],
 [['2', '1', '1', '1'], 2],
 [['1', '1', '1', '1'], 1],
 [['1', '1', '1', '1'], 1],
 [['1', '1', '1', '0'], 0],
 [['4', '5', '5', '4'], 400],
 [['5', '5', '4', '4'], 400],
 [['5', '4', '4', '4'], 320],
 [['4', '4', '4', '3'], 192],
 [['9', '8', '7', '8'], 4032],
 [['8', '7', '8', '7'], 3136]]

# Problem 7


By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [218]:
list_primes[10000]

104743

In [213]:
def primes(highest):
    integers = list(range(2,highest+1)) # nie ma sensu brac 1
    ile_liczb = len(integers)
    temp = []
    for num in range(ile_liczb):
        if integers[num] != 1:
            temp.append(integers[num]) #print(num)
            for n in range(num+1, ile_liczb):
                if integers[n] % integers[num] == 0:
                    integers[n]=1
                else:
                    pass
        else:
            pass
    return temp, len(temp)

list_primes, len_primes = primes(110000)

# solution

Function isPrime(n)
if n=1 then return false
else
if n<4 then return true //2 and 3 are prime
else
if n mod 2=0 then return false
else
if n<9 then return true //we have already excluded 4,6 and 8.
else
if n mod 3=0 then return false
else
r=floor( n ) // n rounded to the greatest integer r so that r*r<=n
f=5
while f<=r
if n mod f=0 then return false (and step out of the function)
if n mod(f+2)=0 then return false (and step out of the function)
f=f+6
endwhile
return true (in all other cases)
End Function

limit=10001
count=1 //we know that 2 is prime
candidate=1
repeat
candidate=candidate+2
if isPrime(candidate) then count=count+1
until count=limit
output candidate

# Problem 6


The sum of the squares of the first ten natural numbers is,
12 + 22 + ... + 102 = 385

The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)2 = 552 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [185]:
def natural_sum(max_int):
    return max_int*(max_int+1)/2

def squares_sum(max_int):
    sq_sum = 0
    for n in range(1,max_int+1):
        sq_sum += n**2
    return sq_sum

number = 100
natural_sum(number)**2-squares_sum(number)

25164150.0

# Problem 5

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [180]:
def prime_factors(number):

    divisor = 2
    factors = [1]
    while number>1:
        while number % divisor == 0:
            number /= divisor
            factors.append(divisor)
        divisor += 1
    return factors


def main(highest):
    multiplyers = list(range(2,highest+1))[::-1] # nie ma sensu brac 1
    ile_liczb = len(multiplyers)
    temp = []
    for num in range(ile_liczb):
        if multiplyers[num] != 1:
            temp.append(multiplyers[num]) #print(num)
            a = prime_factors(multiplyers[num])
            for div in a[1:]:
                for n in range(num+1, ile_liczb):
                    #print('index',n)
                    if multiplyers[n] % div == 0:
                        multiplyers[n]/= div
                    else:
                        pass
                #print(div)
            #print(temp)
        else:
            pass
    product = 1
    for x in temp:
        product *= x
    return product

main(20)
#multiplyers[4-1]=1
#multiplyers

232792560.0

# Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

===========================================================

da sie chyba latwiej to zrobic porownujac listy number_list i number_list[::-1]

In [143]:
def is_palindromic(number):
    d = 1
    check = 0
    number_list = list(str(number))
    num_digits = len(number_list)
    
# even numbers of digits    
    if num_digits % 2 == 0: 
        for d in range(1,int(num_digits/2)+1):
            if number_list[d-1] == number_list[-d]:
                check += 1
            else:
                #print('not palindromic')
                break
        if check == num_digits/2:
            print(number, 'palindromic')
# odd numbers of digits    
    else: 
        #print('nieparzysta')
        for d in range(1,int((num_digits-1)/2)+1):
            if number_list[d-1] == number_list[-d]:
                check += 1
            else:
                #print('not palindromic')
                break
        if check == (num_digits-1)/2:
            print(number, 'palindromic')
            
for first in range(750,1000):
    for second in range(first,1000):
        target_number = first * second
        is_palindromic(target_number)

#target_number =2142312
#is_palindromic(target_number)

696696 palindromic
663366 palindromic
723327 palindromic
619916 palindromic
612216 palindromic
630036 palindromic
666666 palindromic
642246 palindromic
639936 palindromic
675576 palindromic
689986 palindromic
660066 palindromic
729927 palindromic
770077 palindromic
654456 palindromic
696696 palindromic
666666 palindromic
678876 palindromic
747747 palindromic
804408 palindromic
698896 palindromic
807708 palindromic
737737 palindromic
780087 palindromic
802208 palindromic
828828 palindromic
749947 palindromic
801108 palindromic
821128 palindromic
793397 palindromic
809908 palindromic
853358 palindromic
840048 palindromic
855558 palindromic
828828 palindromic
819918 palindromic
824428 palindromic
906609 palindromic
886688 palindromic
861168 palindromic
888888 palindromic

# Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [95]:
target_number = 600851475143

def prime_factors(number):

    divisor = 2
    factors = [1]
    while number>1:
        while number % divisor == 0:
            number /= divisor
            factors.append(divisor)
        divisor += 1
    return factors

a = prime_factors(target_number)
print(a, 'max:', max(a))

[1, 71, 839, 1471, 6857] max: 6857

# Problem 2


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [34]:
limit = 4000000
#limit = 12
a = 1
b = 1
sum_even = 0
while True:
    a, b = b, a+b
    if b % 2 == 0:
        sum_even += b
    if b > limit:
        break
    #print(a, b, sum_even)
print(sum_even)

4613732

# Problem 1


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [12]:
sum(filter(lambda x: (x % 3 == 0) or (x % 5 == 0), range(1000)))

233168